### ISSUE TITLE
CC 4.0 Attribution clauses

### ISSUE THREAD

**Issue by pnorman** [kmewhort/clip#7]
A comparison with the compatibility tool says you can likely release a combination of CC BY 3.0 and your work as CC BY 4.0. This neglects the attribution clause - CC BY 3.0 requires that the CC BY 3.0 source's attribution is at least as prominent as any other authors, regardless of the significances of the contribution of the source (i.e. a small source requires the same attribution as a major source).

CC 4.0 removes this onerous attribution clause, but is hence incompatible. This is an incompatibility not a warning because CC BY 4.0 grants the rights for further downstream users to use the work under its license terms, and you do not have those rights to grant with regard to attribution.

**Comment by kmewhort** [comment]
The tool is a bit too granular to account for slight legal nuances such as this. It doesn't directly map which licenses are compatible with one another, but rather generates a thumbs-up or thumbs-down on-the-fly for all the millions of possible combinations of licenses.  It does this by comparing metadata on the clauses of each different licenses -- in this case of attribution, this isn't much more than whether a license requires metadata or not.

In most cases, if you properly attribute in CC4, this will be compatible with CC3.  The author prominence issue is only going to affect a minority of cases.  To be 100% sure of complying with all the nuances of any license, consulting a lawyer is necessary.  The tool isn't meant to be a replacement for that.
