### ISSUE TITLE
clipol.org is down

### ISSUE THREAD

**Issue by valioDOTch** [kmewhort/clip#9]
The site seems to be down at the moment. :-(

Will it be up again or not?
If not, it might be a good idea to adapt the Readme.

**Comment by jpmckinney** [comment]
I've deployed the app to https://clipol.herokuapp.com/ and am in contact with Kent to get the site back up. See #10

**Comment by jpmckinney** [comment]
It's back up!

**Comment by valioDOTch** [comment]
:+1:
